import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createReferenceHost,createKDNAServer,handleKDNARequest,readResultResponse} from '@aikdna/kdna-web-server';
import {createNextHandlers} from '@aikdna/kdna-web-server/nextjs';
import {createKDNARouter} from '@aikdna/kdna-web-server/express';
import {admitNode} from '@aikdna/kdna-core/node';
import {bytesFor,context,retained,settings,allowAll,inspect,request,upload,withOptionalSupport} from './fixtures.mjs';
const rich=bytesFor('independent-mechanisms.kdna');
const ready=result=>{assert.equal(result.channel,'read_envelope');assert.equal(result.envelope.status,'ready');return result.envelope;};
const code=result=>result.envelope?.diagnostics.find(x=>x.severity==='error')?.code??result.admission_rejection?.code??result.control?.code??result.transport_failure?.code;
function host(retain=false,extra={}){return createReferenceHost({observePolicy:allowAll,...(retain?{retainedSession:retained}:{}),...extra});}
function methods(view){return view.ir.nodes.filter(n=>n.role==='method');}

test('health reports current Core, Read and the public component definition without action authority',async()=>{
 const server=createKDNAServer();try{const response=await server.handle(new Request('http://synthetic.invalid/api/kdna'));assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,service:'kdna-web-server',core:'0.24.0-rc.component-semantics.2',read:'0.3.0-rc.component-semantics.2',component_definition_digest:'sha256:3087cd19542e72322aec19b3015c916d2cfb074fa42e3fd76b3756bb4f097de3',browser:'NOT_EXPOSED_BY_SERVER_HOST',action_authorization:'not_evaluated'});}finally{server.dispose();}
});
for(const retain of [false,true]){
 test(`accepted validation retains exact legacy positive shape (retained=${retain})`,async()=>{const h=host(retain);try{assert.deepEqual(await h.validate(rich),{valid:true,action_authorization:'not_evaluated'});}finally{h.dispose();}});
 const negativeFixtures={'content-digest-mismatch.kdna':'READ_COMPONENT_BINDING_INVALID','known-component-definition-mismatch.kdna':'READ_COMPONENT_DECLARATION_INVALID','presence-with-no-parent.kdna':'READ_METHOD_PRESENCE_INVALID','taxonomy-cycle.kdna':'READ_COMPONENT_GRAPH_CYCLE','wrong-native-binding-target-rehashed.kdna':'READ_COMPONENT_BINDING_INVALID','trailing-meaning-whitespace.kdna':'READ_COMPONENT_CONTENT_INVALID','unknown-contrast-candidate.kdna':'READ_COMPONENT_REFERENCE_INVALID','taxonomy-65-edges.kdna':'READ_COMPONENT_LIMIT_EXCEEDED','aggregate-wrong-proposal_set_digest.kdna':'READ_COMPONENT_ADOPTION_INVALID'};
 for(const file of Object.keys(negativeFixtures)){
  test(`Core valid+blocked rejection survives validate and read: ${file} retained=${retain}`,async()=>{
   const bytes=bytesFor(file),core=await admitNode(bytes);assert.equal(core.status,'rejected');assert.deepEqual(core.states,{core:'valid',interpretation:'blocked'});assert.equal(core.reason,negativeFixtures[file]);
   const h=host(retain);try{assert.deepEqual(await h.validate(bytes),{valid:false,code:core.reason,action_authorization:'not_evaluated',states:core.states,diagnostics:core.diagnostics,component_failure:core.component_failure});const result=await h.read(bytes,await request(rich,'reject:'+file),retain?settings:{});assert.notEqual(result.envelope?.status,'ready');assert.equal(code(result),core.reason);assert.equal(result.envelope?.content??null,null);if(result.envelope){assert.equal(result.envelope.states.core,'valid');assert.equal(result.envelope.states.interpretation,'blocked');}}finally{h.dispose();}
  });
 }
 test(`Core invalid+not_evaluated stays distinct (retained=${retain})`,async()=>{const bytes=Uint8Array.of(1,2,3),core=await admitNode(bytes);assert.equal(core.status,'rejected');assert.equal(core.states.core,'invalid');assert.equal(core.states.interpretation,'not_evaluated');const h=host(retain);try{const v=await h.validate(bytes);assert.equal(v.valid,false);assert.deepEqual(v.states,core.states);assert.deepEqual(v.component_failure,core.component_failure);}finally{h.dispose();}});
}
test('all three supported component types, original content and source digests survive direct Read',async()=>{
 const view=await inspect(rich),h=host();try{const req=await request(rich,'all-components'),env=ready(await h.read(rich,req));assert.deepEqual(env.content.closure.filter(n=>n.role==='method'),methods(view));const types=new Set(env.content.closure.filter(n=>n.role==='method').flatMap(n=>n.value.component_interpretations.map(c=>c.body.kind)));assert.deepEqual([...types].sort(),['candidate-set','discriminator-set','taxonomy']);assert.deepEqual(env.digests,view.digests);assert.equal(env.request_id,req.request_id);assert.equal(env.receipt.request_id,req.request_id);assert.equal(env.receipt.snapshot_id,env.snapshot_id);const wire=readResultResponse({channel:'read_envelope',envelope:env,admission_rejection:null,control:null,transport_failure:null});assert.ok((await wire.arrayBuffer()).byteLength<=req.budget_bytes);}finally{h.dispose();}
});
for(const file of ['explicit-empty-candidate-set.kdna','presence-declared-undeclared.kdna','presence-undeclared-undeclared.kdna','no-parent-method-is-absent.kdna','old-asset.kdna']){
 test(`current graph preserves ordinary, empty and presence distinction: ${file}`,async()=>{const bytes=bytesFor(file),view=await inspect(bytes),h=host();try{const env=ready(await h.read(bytes,await request(bytes,'presence:'+file)));assert.deepEqual(env.content.closure.filter(n=>n.role==='method'),methods(view));if(file==='explicit-empty-candidate-set.kdna')assert.deepEqual(methods(view)[0].value.component_interpretations[0].body,{kind:'candidate-set',items:[]});if(file==='no-parent-method-is-absent.kdna')assert.equal(methods(view).length,0);}finally{h.dispose();}});
}
test('default deny and narrowed policy cannot disclose the component body',async()=>{for(const policy of [undefined,()=>({decision:'allow',scope:[],epoch:'scope:closed',policyId:'closed'})]){const h=createReferenceHost(policy?{observePolicy:policy}:{});try{const r=await h.read(rich,await request(rich,'deny'));assert.notEqual(r.envelope?.status,'ready');assert.equal(r.envelope?.content??null,null);assert.equal(code(r),policy?'READ_SCOPE_DENIED':'READ_HOST_DENIED');}finally{h.dispose();}}});
test('component envelope budgeting rejects instead of truncating a rich body',async()=>{const h=host();try{const r=await h.read(rich,await request(rich,'small',{budget_bytes:1000}));assert.notEqual(r.envelope?.status,'ready');assert.equal(r.envelope?.content??null,null);assert.ok(['READ_BUDGET_INSUFFICIENT','READ_RESPONSE_TOO_SMALL'].includes(code(r)));}finally{h.dispose();}});
test('invalid and old tuple requests are rejected by public Read',async()=>{for(const mutate of [r=>({...r,extra:true}),r=>({...r,tuple:{...r.tuple,core:'kdna.core/0.2.0',ir:'kdna.canonical-ir/0.1.0',read:'kdna.read/0.1.0'}})]){const h=host();try{const result=await h.read(rich,mutate(await request(rich,'bad-request')));assert.notEqual(result.envelope?.status,'ready');assert.equal(result.envelope?.content??null,null);}finally{h.dispose();}}});
test('delivery false never reports ready component disclosure',async()=>{const h=host();try{const r=await h.read(rich,await request(rich,'failed-delivery'),{deliver:()=>false});assert.equal(r.channel,'transport_failure');assert.equal(r.envelope,null);}finally{h.dispose();}});
test('retained rich read issues actual optional handle and expand preserves snapshot/digests',async()=>{
 const bytes=withOptionalSupport(),h=host(true);try{const first=ready(await h.read(bytes,await request(bytes,'initial-rich'),settings));assert.deepEqual(first.content.closure.filter(n=>n.role==='method'),methods(await inspect(bytes)));const handle=first.content.expansion_handles[0];assert.ok(handle);const expanded=ready(await h.read(bytes,await request(bytes,'expanded',{mode:'expand',handle}),settings));assert.equal(expanded.snapshot_id,first.snapshot_id);assert.deepEqual(expanded.digests,first.digests);assert.match(JSON.stringify(expanded.content),/OPTIONAL_COMPONENT_HOST_SUPPORT/);assert.equal(h.retentionState().state,'active');const replay=await h.read(bytes,await request(bytes,'expanded',{mode:'expand',handle}),settings);assert.equal(replay.channel,'transport_failure');}finally{h.dispose();assert.equal(h.retentionState().state,'closed');}
});
test('retained foreign context, changed bytes, and foreign issued handles reject',async()=>{
 const bytes=withOptionalSupport(),a=host(true),b=host(true);try{const req=await request(bytes,'bound'),first=ready(await a.read(bytes,req,settings));await assert.rejects(a.read(bytes,await request(bytes,'foreign'),{...settings,context:{fixture:'server-owned-context'}}),{code:'HOST_CONTEXT_UNVERIFIED'});const changed=new Uint8Array(bytes);changed[0]^=1;await assert.rejects(a.read(changed,await request(bytes,'different'),settings),{code:'HOST_RETAINED_INPUT_MISMATCH'});ready(await b.read(bytes,await request(bytes,'b'),settings));const foreign=await b.read(bytes,await request(bytes,'foreign-handle',{mode:'expand',handle:first.content.expansion_handles[0]}),settings);assert.equal(code(foreign),'READ_HANDLE_UNTRUSTED');}finally{a.dispose();b.dispose();}
});
test('current policy revocation and epoch changes close retained component eligibility',async()=>{for(const mode of ['revoked','epoch']){let revoked=false,epoch='epoch:initial';const h=host(true,{observePolicy:o=>({...allowAll(o),epoch,revoked})});try{ready(await h.read(rich,await request(rich,'policy:first'),settings));if(mode==='revoked')revoked=true;else epoch='epoch:changed';const r=await h.read(rich,await request(rich,'policy:changed'),settings).catch(e=>e);assert.notEqual(r.envelope?.status,'ready');assert.equal(h.retentionState().state,'closed');}finally{h.dispose();}}});
test('retained delivery failure and pre-abort do not issue handles',async()=>{const bytes=withOptionalSupport();for(const mode of ['false','abort']){const h=host(true);try{if(mode==='false'){const r=await h.read(bytes,await request(bytes,'delivery'),{context,deliverResponse:()=>false});assert.equal(r.channel,'transport_failure');}else{const controller=new AbortController();controller.abort();await assert.rejects(h.read(bytes,await request(bytes,'abort'),{...settings,signal:controller.signal}),{code:'HOST_REQUEST_ABORTED'});}assert.equal(h.retentionState().issued_handle_records,0);}finally{h.dispose();}}});
test('Request/Response read body is the formal envelope and never an extra wrapper',async()=>{const server=createKDNAServer({observePolicy:allowAll});try{const req=await request(rich,'service-read'),response=await server.handle(upload('read',rich,req));assert.equal(response.status,200);assert.equal(response.headers.get('x-kdna-channel'),'read_envelope');const raw=await response.arrayBuffer();assert.ok(raw.byteLength<=req.budget_bytes);const env=JSON.parse(Buffer.from(raw));assert.equal(env.status,'ready');assert.equal(env.request_id,req.request_id);assert.equal(env.envelope,undefined);assert.deepEqual(env.content.closure.filter(n=>n.role==='method'),methods(await inspect(rich)));}finally{server.dispose();}});
test('Request validation carries Core blocked states while denied/malformed/budget routes disclose no body',async()=>{const server=createKDNAServer();try{const blocked=await server.handle(upload('validate',bytesFor('taxonomy-cycle.kdna')));const v=await blocked.json();assert.equal(v.valid,false);assert.deepEqual(v.states,{core:'valid',interpretation:'blocked'});const denied=await server.handle(upload('read',rich,await request(rich,'service-deny')));assert.equal(denied.status,422);assert.equal((await denied.json()).content,null);const malformed=await server.handle(new Request('http://synthetic.invalid/api/kdna/read',{method:'POST',body:'bad'}));assert.equal(malformed.status,400);const action=await server.handle(new Request('http://synthetic.invalid/api/kdna/execute',{method:'POST'}));assert.equal(action.status,501);}finally{server.dispose();}});
test('retained service requires real delivery confirmation and records failure',async()=>{const server=createKDNAServer({retainedSession:retained,observePolicy:allowAll});try{const missing=await server.handle(upload('read',rich,await request(rich,'missing')));assert.equal((await missing.json()).error.code,'HOST_DELIVERY_CONFIRMATION_REQUIRED');const response=await server.handle(upload('read',rich,await request(rich,'failure')),{context,deliverResponse:()=>false});assert.equal(response.status,502);assert.equal(response.headers.get('x-kdna-channel'),'transport_failure');assert.equal(await response.text(),'');}finally{server.dispose();}});
test('Next and Express public entries remain available; unsupported retained stateless adaptation rejects',async()=>{assert.equal(typeof createKDNARouter,'function');const router=createKDNARouter({observePolicy:allowAll});assert.equal(typeof router,'function');router.dispose();assert.throws(()=>createNextHandlers({retainedSession:retained}),{code:'HOST_RETAINED_DELIVERY_UNSUPPORTED'});const handlers=createNextHandlers({observePolicy:allowAll});assert.equal(typeof handlers.POST,'function');await assert.rejects(handleKDNARequest(upload('read',rich,await request(rich,'single')),{retainedSession:retained}),{code:'HOST_RETAINED_INSTANCE_REQUIRED'});});
